[package]
name = "rust_cli"
version = "0.1.0"
edition = "2021"

[lib]
name = "rust_cli"
path = "src/lib.rs"

[[bin]]
name = "mybin"
path = "playground/main.rs"

[dependencies]
colored = "2.0.0"
crossterm= "0.25.0"